nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
npmAlwaysAuth: true

npmScopes:
  smonier:
    npmRegistryServer: "https://registry.npmjs.org"
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"